# Config. del nombre y version de la aplicacion
spring.application.name=@project.name@
spring.application.version=@project.version@

# Config. de la logitud max de archivos
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Config. del JWT
security.jwt.client-id=apiexstream
security.jwt.client-secret=4pi3XsTre4m

# Configuracion de JPA y Hibernate
spring.datasource.jndi-name=jdbc/PortalExsDb
spring.datasource.xsa.jndi-name=jdbc/HistXsaDb
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
spring.jpa.properties.hibernate.default_schema=USR_EXS_PORTAL
spring.jpa.properties.hibernate.id.new_generator_mappings=false
spring.jpa.properties.hibernate.jdbc.batch_size=100000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
# Niveles de logging
logging.level.root=INFO

# ubicacion del fichero de logs
management.endpoint.logfile.external-file=${jboss.server.log.dir}/server.log

# exponiendo health/info/loggers
#management.endpoints.web.exposure.include=health,info,beans,mappings,loggers,logfile,logfiles,metrics,env
#management.endpoint.health.show-details=always
#management.metrics.enable.all=true





